name: flutter_shell
description: Flutter Project for Raízen, focused on vehicle management.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5
  intl: ^0.18.1
  sqflite: ^2.3.0
  path: ^1.8.3
  carousel_slider: ^4.2.1
  url_launcher: ^6.1.14

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: Futura
      fonts:
        - asset: assets/fonts/Futura-Bold.otf

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
